#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Stealth + speed helpers for WebVulnX.

Goals (they conflict if you just spray more payloads):
  * look like a real Chrome session (one stable fingerprint — rotating UAs
    is MORE detectable than a single consistent browser)
  * back off the instant a WAF / 429 shows up so the target does not ban us
  * cache identical GETs so crawl + audit + DOM analysis do not triple-hit
  * auto-tune delay: zero on localhost, human-like jitter on remote hosts
"""
from __future__ import annotations

import random
import threading
import time
from typing import Dict, Optional
from urllib.parse import urlsplit

# One stable Chrome 128 fingerprint. Do NOT put "scanner", "vuln", "dark",
# "sqlmap", "burp", "nikto" anywhere in the headers.
CHROME_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
)
CHROME_HEADERS: Dict[str, str] = {
    "User-Agent": CHROME_UA,
    "Accept": ("text/html,application/xhtml+xml,application/xml;q=0.9,"
               "image/avif,image/webp,image/apng,*/*;q=0.8"),
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate",
    "Cache-Control": "max-age=0",
    "Upgrade-Insecure-Requests": "1",
    "Sec-CH-UA": '"Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"',
    "Sec-CH-UA-Mobile": "?0",
    "Sec-CH-UA-Platform": '"Windows"',
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-User": "?1",
    "Sec-Fetch-Dest": "document",
}

WAF_MARKERS = (
    "cloudflare", "captcha", "attention required", "cf-ray",
    "access denied", "unusual traffic", "request blocked",
    "akamai", "incapsula", "imperva", "sucuri", "barracuda",
    "f5 big-ip", "mod_security", "not acceptable", "bot detected",
    "security check", "ray id", "generated by cloudfront",
)


def is_local_target(url: str) -> bool:
    host = (urlsplit(url).hostname or "").lower()
    return host in ("127.0.0.1", "localhost", "::1", "0.0.0.0") or \
        host.startswith("192.168.") or host.startswith("10.") or \
        host.startswith("172.16.") or host.endswith(".local")


class RateGate:
    """Per-client min-interval + exponential backoff on 429/WAF."""

    def __init__(self, min_interval: float = 0.0, jitter: float = 0.0):
        self.min_interval = min_interval
        self.jitter = jitter
        self._lock = threading.Lock()
        self._next = 0.0
        self.strikes = 0

    def wait(self) -> None:
        with self._lock:
            now = time.time()
            extra = random.uniform(0.0, self.jitter) if self.jitter else 0.0
            target = self._next + extra
            self._next = max(now, target) + self.min_interval
        sleep_for = target - now
        if sleep_for > 0:
            time.sleep(sleep_for)

    def punish(self, retry_after: Optional[float] = None) -> None:
        with self._lock:
            self.strikes += 1
            pause = retry_after if retry_after and retry_after > 0 else min(8.0, 1.5 ** self.strikes)
            self.min_interval = min(1.5, max(self.min_interval, 0.25) * 1.6)
            self.jitter = max(self.jitter, 0.15)
            self._next = time.time() + pause

    def reward(self) -> None:
        if self.strikes and self.strikes > 0:
            self.strikes -= 1


def looks_like_waf(status: int, body: str) -> bool:
    if status in (403, 406, 429, 503, 999):
        blob = (body or "")[:2500].lower()
        if status == 429:
            return True
        return any(m in blob for m in WAF_MARKERS)
    blob = (body or "")[:1500].lower()
    return any(m in blob for m in ("cf-browser-verification", "just a moment…",
                                   "checking your browser"))


def retry_after_seconds(headers: Dict) -> Optional[float]:
    raw = ""
    for k, v in (headers or {}).items():
        if k.lower() == "retry-after":
            raw = str(v).strip()
            break
    if not raw:
        return None
    try:
        return float(raw)
    except ValueError:
        return None
